swimming_gym/fornecedores/urls.py
from django.urls import path
from fornecedores import views

app_name = 'fornecedores'

urlpatterns = [
    path('', views.fornecedores_view, name='fornecedores'),
    path('adicionar', views.adicionar_fornecedor, name='adicionar_fornecedor'),
    path('editar/<fornecedor_id>', views.editar_fornecedor, name='editar_fornecedor'),
    path('deletar/<fornecedor_id>', views.delete_fornecedor, name='deletar_fornecedor'),
]

swimming_gym/login/urls.py
from django.urls import path
from login import views

app_name = 'login'

urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

swimming_gym/swimming_gym/urls.py
from django.contrib import admin
from django.urls import path, include
from api.views import CreateUserView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/user/register/", CreateUserView.as_view(), name="register"),
    path("api/token/", TokenObtainPairView.as_view(), name="get_token"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="refresh"),
    path("api-auth/", include("rest_framework.urls")),
    # path("api/", include("api.urls")),
]

swimming_gym/fornecedores/models.py
from django.db import models


class Fornecedor(models.Model):
    nome = models.CharField(max_length=120, verbose_name='Nome')
    telefone = models.CharField(max_length=20, verbose_name='Telefone')
    documento = models.CharField(max_length=20, verbose_name='CPF/CNPJ')
    rua = models.CharField(max_length=250, verbose_name='Logradouro')
    numero = models.CharField(max_length=10, verbose_name='Número')
    bairro = models.CharField(max_length=100, verbose_name='Bairro')
    cidade = models.CharField(max_length=100, verbose_name='Cidade')
    estado = models.CharField(max_length=2, verbose_name='Estado')

    def __str__(self):
        return self.nome

swimming_gym/fornecedores/forms.py
from django import forms
from fornecedores.models import Fornecedor


class FornecedorForm(forms.ModelForm):
    class Meta:
        model = Fornecedor
        fields = [
            'nome',
            'telefone',
            'documento',
            'rua',
            'numero',
            'bairro',
            'cidade',
            'estado'
        ]

    def __init__(self, request, *args, **kwargs):
        super(FornecedorForm, self).__init__(*args, **kwargs)
        if not request.user.is_staff:
            del self.fields['nome']


class EditFornecedorForm(forms.ModelForm):
    class Meta:
        model = Fornecedor
        fields = [
            'nome',
            'telefone',
            'documento',
            'rua',
            'numero',
            'bairro',
            'cidade',
            'estado'
        ]

swimming_gym/fornecedores/views.py
from django.shortcuts import render, redirect, get_object_or_404
from fornecedores.models import Fornecedor
from fornecedores.forms import FornecedorForm, EditFornecedorForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required(login_url='login:login', redirect_field_name='next')
def fornecedores_view(request):
    fornecedores = Fornecedor.objects.all()
    return render(request, 'fornecedores.html', context={
        'title': 'Fornecedores',
        'fornecedores': fornecedores
    })


@login_required(login_url='login:login', redirect_field_name='next')
def adicionar_fornecedor(request):
    if request.method == 'POST':
        form = FornecedorForm(request, request.POST)
        if form.is_valid():
            novo_fornecedor = form.save(commit=False)
            form.save()
            messages.success(request, f'O fornecedor "{novo_fornecedor.nome}" foi adicionado com sucesso!')
            return redirect('fornecedores:fornecedores')
    else:
        form = FornecedorForm(request)

    return render(request, 'adicionar_fornecedor.html', context={
        'title': 'Adicionar fornecedor',
        'form': form
    })


@login_required(login_url='login:login', redirect_field_name='next')
def editar_fornecedor(request, fornecedor_id):
    fornecedor = get_object_or_404(Fornecedor, pk=fornecedor_id)
    if request.method == 'POST':
        form = EditFornecedorForm(request.POST, instance=fornecedor)
        if form.is_valid():
            fornecedor_edit = form.save()
            messages.success(request, f'O fornecedor "{fornecedor_edit.nome}" foi editado com sucesso!')
            return redirect('fornecedores:fornecedores')
    else:
        form = EditFornecedorForm(instance=fornecedor)

    return render(request, 'adicionar_fornecedor.html', context={
        'title': 'Editar fornecedor',
        'form': form
    })


@login_required(login_url='login:login', redirect_field_name='next')
def delete_fornecedor(request, fornecedor_id):
    fornecedor = get_object_or_404(Fornecedor, pk=fornecedor_id)

    fornecedor.delete()
    messages.success(request, f'O fornecedor foi deletado com sucesso!')
    return redirect('fornecedores:fornecedores')

swimming_gym/fornecedores/templates/adicionar_fornecedor.html
{% extends "index.html" %}
{% load bootstrap5 %}
{% block page_title %}
Fornecedores
{% endblock page_title %}

{% block main_content %}
    <a href="{% url "fornecedores:fornecedores" %}" class="btn btn-primary mb-3">
        <span class="fas fa-arrow-left mr-1"></span>
        Voltar
    </a>
    <div class="card-fornecedor">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="btn btn-primary">
                        <span class="fas fa-save"></span>
                        Salvar
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock main_content %}

swimming_gym/fornecedores/templates/fornecedores.html
{% extends "index.html" %}
{% block page_title %}
Fornecedores
{% endblock page_title %}

{% block main_content %}
<a href="{% url "fornecedores:adicionar_fornecedor" %}" class="btn btn-primary mb-3">
    <span class="fas fa-plus mr-1"></span>
    Cadastrar
</a>
<div class="card-table">
    <div class="card">
        <div class="card-body">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Telefone</th>
                        <th>Cidade</th>
                        <th>Opções</th>
                    </tr>
                </thead>
                <tbody>
                    {% for fornecedor in fornecedores %}
                        <tr>
                            <td>{{ fornecedor.nome }}</td>
                            <td>{{ fornecedor.telefone }}</td>
                            <td>{{ fornecedor.cidade }}</td>
                            <td>
                                <div class="dropdown">
                                    <button class="btn btn-dark btn-sm dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                        Opções
                                    </button>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" href="{% url "fornecedores:editar_fornecedor" fornecedor.id %}">Editar</a>
                                        <a class="dropdown-item" href="{% url "fornecedores:deletar_fornecedor" fornecedor.id %}">Deletar</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock main_content %}