swimming_gym/login/urls.py
from django.urls import path
from login import views

app_name = 'login'

urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

swimming_gym/recebimentos/urls.py
from django.urls import path
from recebimentos import views

app_name = 'recebimentos'

urlpatterns = [
    path('', views.recebimentos_views, name='recebimentos'),
    path('adicionar/', views.adicionar_recebimento, name='adicionar_recebimento'),
    path('editar/<recebimento_id>/', views.editar_recebimento, name='editar_recebimento'),
    path('deletar/<recebimento_id>', views.delete_recebimento, name='deletar_recebimento'),
    path('relatorio_faturamento', views.relatorio_faturamento, name="relatorio_faturamento"),
]

swimming_gym/swimming_gym/urls.py
from django.contrib import admin
from django.urls import path, include
from api.views import CreateUserView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/user/register/", CreateUserView.as_view(), name="register"),
    path("api/token/", TokenObtainPairView.as_view(), name="get_token"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="refresh"),
    path("api-auth/", include("rest_framework.urls")),
    # path("api/", include("api.urls")),
]

swimming_gym/recebimentos/models.py
from django.db import models
from alunos.models import Aluno

PAGAMENTO_STATUS = [
    ('pendente', 'Pendente'),
    ('pago', 'Pago'),
    ('cancelado', 'Cancelado'),
]


class Recebimento(models.Model):
    aluno = models.ForeignKey(Aluno, on_delete=models.CASCADE)
    descricao = models.CharField(max_length=255, verbose_name='Descrição')
    valor = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Valor')
    data_emissao = models.DateField(auto_now_add=True, verbose_name='Data de Emissão')
    data_vencimento = models.DateField(verbose_name='Data de Vencimento')
    status = models.CharField(max_length=30, choices=PAGAMENTO_STATUS, default='pendente')

    def __str__(self):
        return self.aluno.nome

swimming_gym/recebimentos/forms.py
from django import forms
from recebimentos.models import Recebimento


class RecebimentoForm(forms.ModelForm):

    class Meta:
        model = Recebimento
        fields = [
            'aluno',
            'descricao',
            'valor',
            'data_vencimento',
            'status',
        ]
        widgets = {
            'data_vencimento': forms.widgets.DateInput(attrs={'type': 'date'})
        }

    def __init__(self, request, *args, **kwargs):
        super(RecebimentoForm, self).__init__(*args, **kwargs)
        if not request.user.is_staff:
            del self.fields['aluno']


class EditRecebimentoForm(forms.ModelForm):

    class Meta:
        model = Recebimento
        fields = [
            'aluno',
            'descricao',
            'valor',
            'data_vencimento',
            'status',
        ]
        widgets = {
            'data_vencimento': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={'class': 'form-control',
                       'placeholder': 'Select a date',
                       'type': 'date'
                       }),
        }

swimming_gym/recebimentos/views.py
from datetime import datetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from recebimentos.models import Recebimento
from recebimentos.forms import RecebimentoForm, EditRecebimentoForm
from recebimentos.tables import RecebimentoTable


@login_required(login_url='login:login', redirect_field_name='next')
def recebimentos_views(request):
    recebimentos = Recebimento.objects.all()
    table = RecebimentoTable(recebimentos)
    return render(request, 'recebimentos.html', context={
        'title': 'Recebimentos',
        'table': table
    })


@login_required(login_url='login:login', redirect_field_name='next')
def adicionar_recebimento(request):
    if request.method == 'POST':
        form = RecebimentoForm(request, request.POST)
        if form.is_valid():
            novo_recebimento = form.save(commit=False)
            form.save()
            messages.success(request,
                             f'O recebimento do aluno "{novo_recebimento.aluno.nome}" foi adicionado com sucesso! ')
            return redirect('recebimentos:recebimentos')
    else:
        form = RecebimentoForm(request)

    return render(request, 'adicionar_recebimento.html', context={
        'title': 'Adicionar recebimentos',
        'form': form
    })


@login_required(login_url='login:login', redirect_field_name='next')
def editar_recebimento(request, recebimento_id):
    recebimento = get_object_or_404(Recebimento, pk=recebimento_id)
    if request.method == 'POST':
        form = EditRecebimentoForm(request.POST, instance=recebimento)
        if form.is_valid():
            edit_recebimento = form.save()
            messages.success(request,
                             f'O recebimento do aluno "{edit_recebimento.aluno.nome}" foi editado com sucesso!')
            return redirect('recebimentos:recebimentos')
    else:
        form = EditRecebimentoForm(instance=recebimento)

    return render(request, 'adicionar_recebimento.html', context={
        'title': 'Editar recebimento',
        'form': form
    })


@login_required(login_url='login:login', redirect_field_name='next')
def delete_recebimento(request, recebimento_id):
    recebimento = get_object_or_404(Recebimento, pk=recebimento_id)

    recebimento.delete()
    messages.success(request, f'O recebimento foi deletado com sucesso!')
    return redirect('recebimentos:recebimentos')


@login_required(login_url='login:login', redirect_field_name='next')
def relatorio_faturamento(request):
    x = Recebimento.objects.filter(status='pago')
    meses = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']
    data = []
    labels = []
    cont = 0
    mes = datetime.now().month + 1
    ano = datetime.now().year
    for i in range(12):
        mes -= 1
        if mes == 0:
            mes = 12
            ano -= 1
        y = sum([i.valor for i in x if i.data_vencimento.month == mes and i.data_vencimento.year == ano])
        labels.append(meses[mes - 1])
        data.append(y)
        cont += 1
    data_json = {'data': data[::-1], 'labels': labels[::-1]}
    return JsonResponse(data_json)

swimming_gym/recebimentos/templates/adicionar_recebimento.html
{% extends "index.html" %}
{% load bootstrap5 %}

{% block page_title %}
Recebimentos
{% endblock page_title %}

{% block main_content %}
    <a href="{% url "recebimentos:recebimentos" %}" class="btn btn-primary mb-3">
        <span class="fas fa-arrow-left mr-1"></span>
        Voltar
    </a>
    <div class="card-pagamentos">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="btn btn-primary">
                        <span class="fas fa-save"></span>
                        Salvar
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock main_content %}

swimming_gym/recebimentos/templates/botao_acoes_recebimentos.html
<div class="dropdown">
    <button class="btn btn-dark btn-sm dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Opções
    </button>
    <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url "recebimentos:editar_recebimento" record.id %}">Editar</a>
        <a class="dropdown-item" href="{% url "recebimentos:deletar_recebimento" record.id %}">Deletar</a>
    </div>
</div>

swimming_gym/recebimentos/templates/recebimentos.html
{% extends "index.html" %}
{% load render_table from django_tables2 %}
{% block page_title %}
Recebimentos
{% endblock page_title %}

{% block main_content %}
<a href="{% url "recebimentos:adicionar_recebimento" %}" class="btn btn-primary mb-3">
    <span class="fas fa-plus mr-1"></span>
    Cadastrar
</a>
<div class="card-table">
    <div class="card">
        <div class="card-body">
            <table class="table table-bordered table-hover">
                {% render_table table %}
            </table>
        </div>
    </div>
</div>
{% endblock main_content %}