swimming_gym/alunos/urls.py
from django.urls import path
from alunos import views

app_name = 'alunos'

urlpatterns = [
    path('', views.alunos_view, name='alunos'),
    path('adicionar', views.adicionar_aluno, name='adicionar_aluno'),
    path('editar/<aluno_id>', views.editar_aluno, name='editar_aluno'),
    path('deletar/<aluno_id>', views.delete_aluno, name='deletar_aluno'),
]

swimming_gym/login/urls.py
from django.urls import path
from login import views

app_name = 'login'

urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

swimming_gym/swimming_gym/urls.py
from django.contrib import admin
from django.urls import path, include
from api.views import CreateUserView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/user/register/", CreateUserView.as_view(), name="register"),
    path("api/token/", TokenObtainPairView.as_view(), name="get_token"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="refresh"),
    path("api-auth/", include("rest_framework.urls")),
    # path("api/", include("api.urls")),
]

swimming_gym/alunos/models.py
from django.db import models


class Aluno(models.Model):
    nome = models.CharField(max_length=120, verbose_name='Nome')
    telefone = models.CharField(max_length=20, verbose_name='Telefone')
    documento = models.CharField(max_length=20, verbose_name='CPF/CNPJ')
    rua = models.CharField(max_length=250, verbose_name='Logradouro')
    numero = models.CharField(max_length=10, verbose_name='Número')
    bairro = models.CharField(max_length=100, verbose_name='Bairro')
    cidade = models.CharField(max_length=100, verbose_name='Cidade')
    estado = models.CharField(max_length=2, verbose_name='Estado')

    def __str__(self):
        return self.nome

swimming_gym/alunos/forms.py
from django import forms
from alunos.models import Aluno


class AlunoForm(forms.ModelForm):
    class Meta:
        model = Aluno
        fields = [
            'nome',
            'telefone',
            'documento',
            'rua',
            'numero',
            'bairro',
            'cidade',
            'estado'
        ]

    def __init__(self, request, *args, **kwargs):
        super(AlunoForm, self).__init__(*args, **kwargs)
        if not request.user.is_staff:
            del self.fields['nome']


class EditAlunoForm(forms.ModelForm):
    class Meta:
        model = Aluno
        fields = [
            'nome',
            'telefone',
            'documento',
            'rua',
            'numero',
            'bairro',
            'cidade',
            'estado'
        ]

swimming_gym/alunos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from alunos.models import Aluno
from alunos.forms import AlunoForm, EditAlunoForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required(login_url='login:login', redirect_field_name='next')
def alunos_view(request):
    alunos = Aluno.objects.all()
    return render(request, 'alunos.html', context={
        'title': 'Alunos',
        'alunos': alunos
    })


@login_required(login_url='login:login', redirect_field_name='next')
def adicionar_aluno(request):
    if request.method == 'POST':
        form = AlunoForm(request, request.POST)
        if form.is_valid():
            novo_aluno = form.save(commit=False)
            form.save()
            messages.success(request, f'O aluno "{novo_aluno.nome}" foi adicionado com sucesso!')
            return redirect('alunos:alunos')
    else:
        form = AlunoForm(request)

    return render(request, 'adicionar_aluno.html', context={
        'title': 'Adicionar aluno',
        'form': form
    })


@login_required(login_url='login:login', redirect_field_name='next')
def editar_aluno(request, aluno_id):
    aluno = get_object_or_404(Aluno, pk=aluno_id)
    if request.method == 'POST':
        form = EditAlunoForm(request.POST, instance=aluno)
        if form.is_valid():
            aluno_edit = form.save()
            messages.success(request, f'O aluno "{aluno_edit.nome}" foi editado com sucesso!')
            return redirect('alunos:alunos')
    else:
        form = EditAlunoForm(instance=aluno)

    return render(request, 'adicionar_aluno.html', context={
        'title': 'Editar aluno',
        'form': form
    })


@login_required(login_url='login:login', redirect_field_name='next')
def delete_aluno(request, aluno_id):
    aluno = get_object_or_404(Aluno, pk=aluno_id)
    aluno.delete()
    messages.success(request, f'O aluno foi deletado com sucesso!')
    return redirect('alunos:alunos')

swimming_gym/alunos/templates/adicionar_aluno.html
{% extends "index.html" %}
{% load bootstrap5 %}
{% block page_title %}
Alunos
{% endblock page_title %}
{% block main_content %}
    <a href="{% url "alunos:alunos" %}" class="btn btn-primary mb-3">
        <span class="fas fa-arrow-left mr-1"></span>
        Voltar
    </a>
    <div class="card-fornecedor">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="btn btn-primary">
                        <span class="fas fa-save"></span>
                        Salvar
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock main_content %}

swimming_gym/alunos/templates/alunos.html
{% extends "index.html" %}
{% block page_title %}
Alunos
{% endblock page_title %}

{% block main_content %}
<a href="{% url "alunos:adicionar_aluno" %}" class="btn btn-primary mb-3">
    <span class="fas fa-plus mr-1"></span>
    Cadastrar
</a>
<div class="card-table">
    <div class="card">
        <div class="card-body">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Telefone</th>
                        <th>Cidade</th>
                        <th>Opções</th>
                    </tr>
                </thead>
                <tbody>
                    {% for aluno in alunos %}
                        <tr>
                            <td>{{ aluno.nome }}</td>
                            <td>{{ aluno.telefone }}</td>
                            <td>{{ aluno.cidade }}</td>
                            <td>
                                <div class="dropdown">
                                    <button class="btn btn-dark btn-sm dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                        Opções
                                    </button>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" href="{% url "alunos:editar_aluno" aluno.id %}">Editar</a>
                                        <a class="dropdown-item" href="{% url "alunos:deletar_aluno" aluno.id %}">Deletar</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock main_content %}